// SPIKE 0009 / question 2, the fix: embed the 12 regular files plus a MANIFEST
// of the 18 symlinks, then replay the links at extraction time.
//
// Rejected alternatives:
//
//   - Dereference the symlinks before embedding. Correct and stupid: it turns
//     one 7.5 MB libllama into three copies, ~14 MB -> ~40 MB per platform.
//     core/build.sh:125 already refuses this for the same reason.
//   - Reconstruct links by pattern at extract time (libfoo.dylib is "probably"
//     the newest libfoo.N.dylib). Guessing at a linker contract.
//
// The manifest is generated by the build, so it cannot drift from what shipped.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

type manifest struct {
	Links map[string]string `json:"links"` // name -> target, may chain
}

// Extract writes the embedded closure into dir. It is idempotent and atomic:
// content goes to a temp directory and is renamed into place, so a killed
// process can never leave a half-extracted closure that dlopen would then load.
func Extract(src fs.FS, root, dir string) (string, error) {
	// A stamp file is what makes the second run free. Checking every file's hash
	// on every process start would cost more than the load it protects.
	stamp := filepath.Join(dir, ".complete")
	if _, err := os.Stat(stamp); err == nil {
		return dir, nil
	}

	tmp := dir + ".tmp-" + fmt.Sprint(os.Getpid())
	if err := os.MkdirAll(tmp, 0o755); err != nil {
		return "", err
	}
	defer os.RemoveAll(tmp)

	var man manifest
	if b, err := fs.ReadFile(src, root+"/links.json"); err == nil {
		if err := json.Unmarshal(b, &man); err != nil {
			return "", fmt.Errorf("link manifest is unreadable: %w", err)
		}
	}

	err := fs.WalkDir(src, root, func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		b, err := fs.ReadFile(src, p)
		if err != nil {
			return err
		}
		out := filepath.Join(tmp, filepath.Base(p))
		// 0o755: these are loadable objects, and on some platforms the loader
		// cares. Cheap to get right, miserable to debug.
		return os.WriteFile(out, b, 0o755)
	})
	if err != nil {
		return "", err
	}

	// Replay the links. Order does not matter: a symlink may point at a name
	// that does not exist yet, and resolution happens at load time.
	for name, target := range man.Links {
		_ = os.Remove(filepath.Join(tmp, name))
		if err := os.Symlink(target, filepath.Join(tmp, name)); err != nil {
			return "", fmt.Errorf("could not recreate %s -> %s: %w", name, target, err)
		}
	}

	if err := os.WriteFile(filepath.Join(tmp, ".complete"), []byte("1"), 0o644); err != nil {
		return "", err
	}
	os.RemoveAll(dir)
	if err := os.MkdirAll(filepath.Dir(dir), 0o755); err != nil {
		return "", err
	}
	if err := os.Rename(tmp, dir); err != nil {
		// Another process won the race and extracted the same bytes. That is a
		// success, not a conflict.
		if _, serr := os.Stat(stamp); serr == nil {
			return dir, nil
		}
		return "", err
	}
	return dir, nil
}

// cacheKey ties the extracted directory to the exact bytes embedded, so a
// binding upgrade cannot serve a stale closure out of the cache -- the bug
// already fixed once for the downloaded natives (fetch.go, BridgeVersion).
func cacheKey(src fs.FS, root string) string {
	h := sha256.New()
	_ = fs.WalkDir(src, root, func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		b, _ := fs.ReadFile(src, p)
		h.Write([]byte(p))
		h.Write(b)
		return nil
	})
	return hex.EncodeToString(h.Sum(nil))[:16]
}
